const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS'
const UPDATE_CLIENT = 'UPDATE_CLIENT'
const DELETE_CLIENT = 'DELETE_CLIENT'
const CREATE_CLIENT = 'CREATE_CLIENT'
const SET_LOAD = 'SET_LOAD'
export default {
    GET_ALL_CLIENTS,
    CREATE_CLIENT,
    UPDATE_CLIENT,
    DELETE_CLIENT,
    SET_LOAD,
}